"""add username to users

Revision ID: a8f2e1c4b9d0
Revises: 531c33bf5433
Create Date: 2026-06-04 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f2e1c4b9d0'
down_revision: Union[str, None] = '531c33bf5433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Generate usernames for existing users
    op.execute("""
        UPDATE users 
        SET username = CONCAT(
            SUBSTRING(MD5(RANDOM()::TEXT) FROM 1 FOR 11)
        )
        WHERE username IS NULL
    """)
    
    # Make username non-nullable after populating
    op.alter_column('users', 'username', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
